baseurl = "https://2025.gophercon.sg/"
languageCode = "en-SG"
title = "GopherCon Singapore 2025"
theme = "gopherconsg-2023"

[params]
  name = "GopherCon Singapore"
  description = "GopherCon Singapore is a Go programming language (Golang) conference in Southeast Asia."
  ogimage = "gopherconsg202x-og.png"
  logo = "gopherconsg202x-long.png" 

[params.ticket]
  buttonText = "Get Your Ticket Now"
  link = "/#tickets"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
